
stages:
    - build
    - test
    - build_image

cache:
    paths:
        - node_modules

install_dependencies:
    stage: build
    script:
        - npm install
    tags:
        - node
    
running_test:
    stage: test
    script: npm test
    tags:
        - node

build_image:
    stage: build_image
    script:
        - echo "Building and pushing docker image"     
        - docker login -u $dockerHubUserName -p $dockerHubPassword                 
        - docker build -t nodeapi .
        - docker tag nodeapi $dockerHubUserName/nodeapi        
        - docker push $dockerHubUserName/nodeapi
    tags:
        - node