stages:
    - build
    - test
    - build_image

cache:
    paths:
        - node_modules

install_dependencies:
    stage: build
    script:
        - npm install

    tags:
        - node
    
testing_testing:
    stage: test
    script: npm test
    tags:
        - node

build_image:
    stage: build_image
    script:
        - echo "$ImageRegUser"
        - echo "$BUILD_VERSION"
        - docker build -t nodeapi:$BUILD_VERSION .
    tags:
        - node