stages:
    - build
    - test
    - build_image

cache:
    paths:
        - node_modules

install_dependencies:
    stage: build
    script:
        - npm install

    tags:
        - node
    
testing_testing:
    stage: test
    script: npm test
    tags:
        - node

build_image:
    stage: build_image
    script:
        - echo "Building and pushing docker image"
        - echo $dockerHubUserName
        - docker login -u $dockerHubUserName -p $dockerHubPassword                 
        - docker build -t nodeapi .
        - docker tag nodeapi "${dockerHubUserName}"/nodeapi:latest
        - docker push "${dockerHubUserName}"/nodeapi:latest
    tags:
        - node