stages:
    - build
    - test

cache:
    paths:
        - node_modules

install_dependencies:
    stage: build
    script:
        - npm install
           
    tags:
        - node
    
testing_testing:
    stage: test
    script: npm test
    tags:
        - node